openapi: '3.0.0'
servers:
  - url: 'https://api.nasa.gov/planetary'
    description: 'NASA APOD API Server'
info:
  contact:
    name: Jon
  version: '1.0.0'
  title: 'Apod API'
  description: This API provides access to the Apod service, which offers astronomy pictures of the day.
  termsOfService: 'https://apod.nasa.gov/apod/lib/about_apod.html'
  license: 
    name: 'NASA Open Source Agreement'
    url: 'https://www.nasa.gov/sites/default/files/atoms/files/nasa_open_source_agreement_1.3.pdf'
paths:
  /apod:
    get:
      summary: 'Get Astronomy Picture of the Day'
      description: 'Retrieves the Astronomy Picture of the Day (APOD) along with its explanation.'
      operationId: 'getApod'
      parameters:
        - name: 'api_key'
          in: query
          required: true
          schema:
            type: 'string'
          example: 'DEMO_KEY'
          description: 'API key for authentication.'
        - name: 'date'
          in: 'query'
          required: false
          schema:
            type: 'string'
            format: 'date'
          description: 'Date for which to retrieve the APOD. Format: YYYY-MM-DD.'
          example: '2023-10-01'
      responses:
        '200':
          description: 'Successful response with APOD data.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApodResponse'
        '400':
          description: 'Bad request, possibly due to missing or invalid parameters.'
          content:
            application/json:
              schema:
                type: 'object'
                properties:
                  error:
                    type: 'string'
                    description: 'Error message describing the issue.'
        '401':
          description: 'Unauthorized, invalid API key.'
        '404':
          description: 'Not found, possibly a wrong URI'
        '429':
          description: 'Too many requests, rate limit exceeded.'
components:
  securitySchemes:
    ApiKey:
      type: 'apiKey'
      in: 'query'
      name: 'api_key'
  schemas:
    ApodResponse:
      type: 'object'
      properties:
        date:
          type: 'string'
          format: 'date'
        explanation:
          type: 'string'
        media_type:
          type: 'string'
        service_version:
          type: 'string'
        title:
          type: 'string'
        url:
          type: 'string'
        hd_url:
          type: 'string'
          description: 'URL for the high-definition version of the image.'
      required:
        - date
        - explanation
        - media_type
        - service_version
        - title
        - url

security:
  - ApiKey: []